info:
    path: bin/Menu
    version: 1.0
    Developer: Sattvik Chakravarthy
    Contributors: ''

parameters:
    views:
        default:
            menu:
                type: text
                maxLength: 50
                defaultValue: mainmenu
