<?php if(!defined('KLONDIKE_VER')) die("Access denied!"); ?>
<?php
    
    global $_APPS;
    $_APPS = array(); // Global array that maintains Apps loaded
    
    abstract class App {
        protected $_APP; // Parsed YAML Data related to the app
        protected $_CONTENT; // HTML Independend content generated by the app
        protected $APP_ID; // Unique ID for each app
        
        public function init($app, $appId) {
            $this->_APP = $app;
            $this->APP_ID = $appId;
            if ( !isset($app['template']) ) $app['template'] = 'content';
            $this->_CONTENT = new Content($app['template'], $app['subregions']);
            $this->controller();
        }
        
        protected function view() { // This function will be called on each instance of an App
            $this->_CONTENT->Clear();
            if( 'none' != $this->_APP['view'])
                call_user_func_array(array($this, $this->_APP['view'] . '_view'), array());
        }
        
        protected function controller() { // This function will be called only once for each unique APP_ID
            if( 'none' != $this->_APP['controller'])
                call_user_func_array(array($this, $this->_APP['controller'] . '_action'), array());
        }
        
        public function __toString() {
            $this->view();
            return (string)$this->_CONTENT; // This works, It generates HTML according to the current template
        }
        
        public function getApp() {
            return $this->_APP;
        }
    }
?>