info:
    path: bin/CustomHtml
    version: 1.0
    Developer: Sattvik Chakravarthy
    Contributors: ''

parameters:
    views:
        default:
            title:
                type: string
                maxLength: 50
                defaultValue: CustomHtml
            text:
                type: string
                defaultValue: Edit this text
