info:
    path: bin/CustomHtml
    version: 1.0
    Developer: Sattvik Chakravarthy
    Contributors: ''

parameters:
    views:
        default:
            title:
                type: text
                defaultValue: CustomHtml
            text:
                type: largetext
                defaultValue: Edit this text
